--Start Writing Table ddls
DROP TABLE BANKCUSTOMERTESTBULK;

CREATE TABLE BANKCUSTOMERTESTBULK
(
	CUSTID NUMERIC(9,0)  NOT NULL  ,
	CUSTNAME CHARACTER VARYING(256)  ,
	CUSTCITY CHARACTER VARYING(256) ,
	BankCustomerTestBulkVer NUMERIC (4, 0)  NOT NULL ,
	dmLastUpdateDate	TIMESTAMP WITH TIME ZONE	NOT NULL  ,
	PRIMARY KEY ( 
	CUSTID  )
);
DROP TABLE BANKCUSTOMERTESTCLASS;

CREATE TABLE BANKCUSTOMERTESTCLASS
(
	CUSTID NUMERIC(9,0)  NOT NULL  ,
	CUSTNAME CHARACTER VARYING(256)  ,
	CUSTDATE DATE  ,
	CUSTCHAR CHARACTER VARYING(1) ,
	BankCustomerTestClassVer NUMERIC (4, 0)  NOT NULL ,
	dmLastUpdateDate	TIMESTAMP WITH TIME ZONE	NOT NULL  ,
	PRIMARY KEY ( 
	CUSTID  )
);
--End Writing Table ddls
--Start Writing Index ddls
--End Writing Index ddls
--Start Writing Keys ddls
--End Writing Keys ddls
--Start Writing Sequence ddls
--End Writing Sequence ddls
